/**
 * Earth Jukebox — Historical Solar Weather Events Database & Time Machine
 * Reconstructed heliophysics telemetry for historic geomagnetic storms & milestones.
 */

const HISTORICAL_EVENTS = [
  {
    id: "live",
    year: "NOW",
    title: "DSCOVR Real-Time Orbit",
    subtitle: "Lagrange Point 1 Live Telemetry",
    category: "Live Satellite Stream",
    stormScale: "Dynamic",
    speed: 350.7,
    density: 2.74,
    temperature: 46113,
    bz: -0.84,
    bt: 3.48,
    kpIndex: 2,
    description: "Operational real-time solar wind streaming from the DSCOVR and ACE spacecraft stationed 1.5 million kilometers sunward.",
    soundCharacteristics: "Pulsing fundamental bass drone with intermittent crystalline aurora bells modulated by real-time magnetic shifts.",
    visualCharacteristics: "Gentle solar wind particle stream with stable magnetospheric bow-shock and subtle polar auroral breathing.",
    scientificContext: "L1 orbit provides 15 to 45 minutes of advance warning before solar wind gusts collide with Earth's magnetosphere.",
    historyBadge: "LIVE STREAM",
    isReconstruction: false
  },
  {
    id: "carrington",
    year: "1859",
    title: "The Carrington Event",
    subtitle: "The Solar Leviathan (September 1–2, 1859)",
    category: "Superstorm",
    stormScale: "G5+",
    speed: 1850.0,
    density: 58.0,
    temperature: 540000,
    bz: -34.5,
    bt: 52.0,
    kpIndex: 9,
    description: "The most intense geomagnetic storm ever recorded. Richard Carrington observed a white-light solar flare that triggered a CME hitting Earth in just 17.6 hours.",
    soundCharacteristics: "Colossal acoustic wall of sound: deep roaring sub-bass thunder beneath intense, piercing high-frequency sirens with frantic, cascading arpeggios.",
    visualCharacteristics: "Extreme compression of Earth's magnetic bow shock down to geostationary orbit; blazing crimson and violet auroras stretching down to tropical latitudes (Cuba, Hawaii).",
    scientificContext: "Historical reconstruction based on ground magnetometer recordings at Colaba and Greenwich. Telegraph wires threw sparks, set paper on fire, and operated with batteries disconnected.",
    historyBadge: "HISTORICAL RECONSTRUCTION",
    isReconstruction: true
  },
  {
    id: "halloween",
    year: "2003",
    title: "Halloween Solar Storms",
    subtitle: "Active Region 486 (October 19–November 5, 2003)",
    category: "Extreme CME",
    stormScale: "G5",
    speed: 1040.0,
    density: 35.0,
    temperature: 320000,
    bz: -24.0,
    bt: 38.0,
    kpIndex: 9,
    description: "A series of powerful solar flares and coronal mass ejections during Solar Cycle 23, including an X28+ flare that saturated satellite detectors.",
    soundCharacteristics: "Turbulent, heavily distorted low-end rumble layered with sharp resonant mid-range sweeps and high-velocity wind noise.",
    visualCharacteristics: "Violent plasma shockwave impacting the magnetopause; satellites entered safe mode and astronauts on the ISS took shelter in the Zvezda module.",
    scientificContext: "Caused a regional power blackout in Malmö, Sweden, damaged electrical transformers in South Africa, and disrupted trans-polar airline navigation.",
    historyBadge: "MEASURED TELEMETRY",
    isReconstruction: false
  },
  {
    id: "may2024",
    year: "2024",
    title: "Mother's Day Superstorm",
    subtitle: "Active Region 3664 (May 10–12, 2024)",
    category: "Modern G5 Storm",
    stormScale: "G5",
    speed: 860.0,
    density: 44.0,
    temperature: 340000,
    bz: -19.5,
    bt: 31.0,
    kpIndex: 9,
    description: "The strongest geomagnetic storm in over two decades. Multiple CMEs merged in transit (cannibal CME), hammering Earth's magnetic shield.",
    soundCharacteristics: "Rich polyphonic choir of shimmering frequencies; rhythmic bell clusters alternating with surging drone dynamics.",
    visualCharacteristics: "Spectacular global auroral oval expanding into southern Europe, central India, Mexico, and Australia. STEVE and SAR arc atmospheric light emissions.",
    scientificContext: "Real-time measurements recorded by DSCOVR. Generated global GNSS and GPS precision degradation while modern electrical grids successfully absorbed the induced currents.",
    historyBadge: "MEASURED TELEMETRY",
    isReconstruction: false
  },
  {
    id: "quebec1989",
    year: "1989",
    title: "Quebec Blackout Storm",
    subtitle: "Solar Flare of March 13, 1989",
    category: "Severe Grid Disturbance",
    stormScale: "G5",
    speed: 920.0,
    density: 28.0,
    temperature: 280000,
    bz: -21.0,
    bt: 32.0,
    kpIndex: 9,
    description: "A CME produced geomagnetically induced currents (GICs) that collapsed the Hydro-Québec power grid in less than 90 seconds, leaving 6 million people in the dark.",
    soundCharacteristics: "Pulsing electrical hum, low-frequency pressure oscillations, and dramatic timbral dropouts reflecting the grid collapse.",
    visualCharacteristics: "Rapid magnetospheric reconnection feeding millions of amperes of electrical current into Earth's ionosphere.",
    scientificContext: "Historical event that permanently revolutionized power grid space weather hardening standards across North America and Europe.",
    historyBadge: "HISTORICAL RECONSTRUCTION",
    isReconstruction: true
  },
  {
    id: "nearmiss2012",
    year: "2012",
    title: "The 2012 Solar Near-Miss",
    subtitle: "STEREO-A Observation (July 23, 2012)",
    category: "Carrington-Class CME",
    stormScale: "G5+",
    speed: 2200.0,
    density: 64.0,
    temperature: 610000,
    bz: -45.0,
    bt: 68.0,
    kpIndex: 9,
    description: "A monster CME with speed exceeding 2,000 km/s erupted from the Sun, directly crossing Earth's orbital path—just one week after Earth had passed that location.",
    soundCharacteristics: "Terrifying, hyper-accelerated acoustic velocity; supersonic carrier frequencies and maximum harmonic saturation.",
    visualCharacteristics: "Blinding solar coronal burst with dense shock front tearing through the heliosphere.",
    scientificContext: "Observed in-situ by NASA's STEREO-A spacecraft. If it had hit Earth, analysts estimated economic impacts exceeding $2 trillion.",
    historyBadge: "STEREO-A TELEMETRY",
    isReconstruction: false
  },
  {
    id: "minimum",
    year: "2019",
    title: "Quiet Solar Minimum",
    subtitle: "Solar Cycle 24/25 Transition",
    category: "Cosmic Calm",
    stormScale: "G0",
    speed: 310.0,
    density: 1.8,
    temperature: 22000,
    bz: 2.8,
    bt: 2.2,
    kpIndex: 0,
    description: "A pristine, spot-free Sun during deep solar minimum. The solar wind is slow, laminar, and gentle.",
    soundCharacteristics: "Ethereal, meditative ambient drone with pure harmonic intervals and quiet, breathing noise textures.",
    visualCharacteristics: "Earth's magnetosphere extends peacefully sunward with minimal compression and quiescent polar caps.",
    scientificContext: "Ideal baseline representing the undisturbed heliosphere, allowing cosmic rays to penetrate deeper into the solar system.",
    historyBadge: "MEASURED TELEMETRY",
    isReconstruction: false
  },
  {
    id: "coronal",
    year: "CYCLIC",
    title: "Coronal Hole Fast Stream",
    subtitle: "Recurrent Heliospheric Plasma Stream",
    category: "High-Speed Wind",
    stormScale: "G1",
    speed: 680.0,
    density: 5.5,
    temperature: 160000,
    bz: -4.5,
    bt: 8.5,
    kpIndex: 4,
    description: "Open magnetic field lines on the solar surface allow unhindered solar wind to blast into interplanetary space, repeating every 27 days as the Sun rotates.",
    soundCharacteristics: "Rhythmic, gusty pulsations with shimmering midrange texture and steady musical cadence.",
    visualCharacteristics: "Continuous high-speed particle stream producing steady auroral displays across high latitudes.",
    scientificContext: "A primary driver of minor-to-moderate geomagnetic activity during the declining phase of the 11-year solar cycle.",
    historyBadge: "MEASURED TELEMETRY",
    isReconstruction: false
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { HISTORICAL_EVENTS };
}
